Cargo.lock
graph-gateway/Cargo.toml
graph-gateway/src/client_query.rs

- feat: new IP blocker (#648)
- fix: cost models query (#656)
- fix: indexer response queue handling (a1457e8)
- feat: indexer-selection improvements (24c8cf1)
- replace `geoip_database`, `geoip_blocked_countries` with `ip_blocker_db`

release 20.0.0

---

Cargo.lock
graph-gateway/Cargo.toml

- feat: make BadIndexers error more verbose (aeff546)
- fix: indexer response handling (ac98eb1)

release 20.0.1

---

gateway-framework/src/chains.rs
gateway-framework/src/lib.rs
graph-gateway/src/client_query.rs
graph-gateway/src/client_query/context.rs
graph-gateway/src/lib.rs
graph-gateway/src/main.rs

Not more going on than it says in the title of the PR.

refactor: move chains and chain readers to framework

---

Cargo.lock
Cargo.toml
graph-gateway/Cargo.toml

- update candidate-selection (b3f6d3b)

release 20.0.3

---

Cargo.lock
gateway-framework/Cargo.toml
graph-gateway/Cargo.toml

- feat: add support for gateway to reject SQL queries (#712)
- fix: disable Nagle's algorithm (#742)
- fix: remove retry loop (#744)

release 20.1.3

---

Cargo.lock
graph-gateway/Cargo.toml

- fix: inefficiencies in processing Agora contexts (#747)

release 20.1.4

---

gateway-framework/src/topology/network.rs
graph-gateway/src/network.rs
graph-gateway/src/network/internal.rs

Minor changes to the `network` module exposed API to reduce the noise in PR #750

chore(graph-gateway): simplify the network module exposed api

---

graph-gateway/src/block_constraints.rs

- fix: inefficiencies in processing Agora contexts (#747, #752, dbc5a0b, e4ebfe5)

fix: block constraint rewrite fallbacks

---

graph-gateway/src/network/internal.rs
graph-gateway/src/network/service.rs
graph-gateway/src/network/snapshot.rs

feat(graph-gateway): add support to resolve transferred to L2 subgraphs

---

graph-gateway/src/network/indexer_indexing_progress_resolver.rs
graph-gateway/src/network/internal.rs
graph-gateway/src/network/snapshot.rs

This PR addresses this comment: https://github.com/edgeandnode/gateway/pull/769#discussion_r1613800263

refactor(graph-gateway): update network indexing progress naming

---

Cargo.lock
graph-gateway/Cargo.toml
graph-gateway/src/client_query.rs
graph-gateway/src/subgraph_studio.rs

- fix: re-introduce retry loop (#772)
- fix: update indexer-selection
- fix: zero_allocation penalty on multiple indexers (https://github.com/edgeandnode/candidate-selection/commit/cf5d1790ecb7784f7adec51477c7a3033fb99989)
- increase zero allocation penalty multiplier to 0.9 (https://github.com/edgeandnode/candidate-selection/commit/4c4e08f95a9fe31fda037ca68125418d249f8e62)
- add floor to latency score (https://github.com/edgeandnode/candidate-selection/commit/373e70269ff38d78ade629bb35ea45199f2f1b45)
- feat: add indexer label to indexer_query metrics (#775, f76ea1a)
- remove SQL constraints (#768)
- remove subscriptions contract auth (#782, 034a4a9)

release 20.2.0

---

graph-gateway/src/network/internal/snapshot.rs
graph-gateway/src/network/service.rs

fix(graph-gateway): add network service update interval timer

---

Cargo.lock
gateway-framework/Cargo.toml
gateway-framework/src/chains.rs
gateway-framework/src/scalar/receipts.rs
gateway-framework/src/topology/mod.rs
graph-gateway/src/client_query.rs
graph-gateway/src/main.rs

Synchronous locks here result in better performance.

fix: use synchronous locks for receipt management

---

Cargo.lock
graph-gateway/Cargo.toml
graph-gateway/src/block_constraints.rs
graph-gateway/src/client_query.rs
graph-gateway/src/indexer_client.rs
graph-gateway/src/network/indexer_indexing_progress_resolver.rs
graph-gateway/src/network/indexer_version_resolver.rs
graph-gateway/src/network/internal/snapshot.rs
graph-gateway/src/network/service.rs

- fix: reduce log noise from candidates
- fix: increase indexer version timeout
- fix: detect nested introspection
- feat: add log for indexer errors

 release 21.2.1

---

Cargo.lock
graph-gateway/Cargo.toml
graph-gateway/src/block_constraints.rs
graph-gateway/src/network/internal/pre_processing.rs
graph-gateway/src/network/service.rs
graph-gateway/src/network/subgraph_client.rs

- extend TTL to max
- fix: reduce depth of query introspection check
- fix: handle manifest without network

release 21.2.2

---

graph-gateway/src/indexers/cost_models.rs
graph-gateway/src/indexers/indexing_progress.rs
graph-gateway/src/network/indexer_indexing_cost_model_resolver.rs
graph-gateway/src/network/indexer_indexing_progress_resolver.rs
graph-gateway/tests/it_indexers_cost_models.rs
graph-gateway/tests/it_indexers_status_indexing_progress.rs

This PR improves the current indexers' cost model resolution error reporting.

refactor(graph-gateway): improve indexer cost model fetch errors

---

graph-gateway/src/indexers/public_poi.rs
graph-gateway/src/network/indexer_indexing_poi_resolver.rs
graph-gateway/src/network/internal/indexer_processing.rs
graph-gateway/src/network/internal/state.rs
graph-gateway/src/network/service.rs
graph-gateway/tests/it_indexers_status_public_pois.rs

This PR improves the current indexers' Public POIs fetch error reporting.

refactor(graph-gateway): improve indexer public POIs fetch errors

---

graph-gateway/src/client_query.rs

Only apply `TooFarBehind` filter if some indexer candidate is close enough to chain head.

fix: selectively apply TooFarBehind filter

---

gateway-framework/src/errors.rs
graph-gateway/src/client_query.rs
graph-gateway/src/main.rs

feat: direct indexer query API

---

graph-gateway/src/main.rs
graph-gateway/src/reports.rs

feat: add to indexer & client query kafka messages

---

Cargo.lock
graph-gateway/Cargo.toml

- feat: add to indexer & client query kafka messages (#879)
- fix: add optimistic progress to indexing status report (#887)
- feat: add rate limiter for L1 deprecation (#889, #898)
- fix: handle indexer-service error format (#896)
- fix: remove block constraint rewrites (#895)

release 22.1.0

---

Cargo.lock
Cargo.toml
graph-gateway/Cargo.toml
graph-gateway/src/block_constraints.rs
graph-gateway/src/client_query.rs

- fix: block data probe rewrite
- fix: indexer address serialization

release 22.1.1

---

Cargo.lock
Cargo.toml
graph-gateway/Cargo.toml
graph-gateway/src/network/indexer_indexing_poi_resolver.rs
graph-gateway/src/network/service.rs
graph-gateway/src/network/subgraph_client.rs

- feat(reports): add request & response bytes (#901)
- fix: check block timestamp in network subgraph client (#902)
- fix: network subgraph queries

release 22.1.2

---

Cargo.lock
Cargo.toml

- fix: indexer response status codes (5823242)

release 22.2.1

---

Cargo.lock
Cargo.toml

- feat: reduce cost model support (#974)
- feat: remove query rewrites (#975)

release 24.2.0

---

Cargo.lock
Cargo.toml
src/block_constraints.rs
src/chain.rs
src/chains.rs
src/client_query.rs
src/indexer_client.rs
src/network/subgraph_client.rs
src/reports.rs

- revert: remove query rewrites

release 24.2.1

---

Cargo.lock
Cargo.toml
src/auth.rs
src/block_constraints.rs
src/chain.rs
src/client_query/context.rs
src/config.rs
src/exchange_rate.rs
src/indexer_client.rs
src/main.rs
src/receipts.rs
src/vouchers.rs

fix: remove ethers deps

---

src/config.rs
src/indexers/public_poi.rs
src/main.rs
src/network/indexer_indexing_poi_blocklist.rs
src/network/service.rs

feat: add /poi_blocklist route

---

Cargo.lock
Cargo.toml

- fix: client_request span triggers (#1002)
- refactor: merge resolvers and blocklists (#1003)

release 26.1.0

---

Cargo.lock
Cargo.toml

- feat: sample attestation reports (#1009)

release 26.1.1

---

Cargo.lock
Cargo.toml

- feat: dynamic blocklist (#1008)
- remove `blocked_indexers`
- remove `poi_blocklist`
- add `blocklist`

release 27.0.0

---

Cargo.lock
Cargo.toml
src/client_query.rs
src/client_query/query_selector.rs
src/indexer_client.rs
src/main.rs
src/middleware/legacy_auth.rs

- fix: logs missing request_id (#1022)
- fix: log non-200 indexer response body (d6de270)

release 27.0.1

---

Cargo.lock
Cargo.toml

- fix: replace network subgraph processing timeout with warning (#1045)

release 27.0.3

---

Cargo.lock
Cargo.toml

- feat: add subgraph ID to reports (#1047)

release 27.1.0

---

Cargo.lock
Cargo.toml
src/network/host_filter.rs

- [fix: move logs out of middleware](https://github.com/edgeandnode/gateway/commit/5b4bd0bd5fd056593f1da6fd11ee4818adbf485c)

release 27.1.1

---

Cargo.lock
Cargo.toml

- fix: remove Agora dependency (#1093)

release 27.1.4

---

Cargo.lock
Cargo.toml

- fix: drop API key event consumer to avoid buggy offset caching (#1104)

release 27.2.1

---

Cargo.lock
Cargo.toml
src/middleware/legacy_auth.rs

release 27.2.3
