edgeandnode/gateway

- graph-gateway/src/main.rs
An indexer trying to /collect-receipts and is failing with http 413. Their payload is 2.8MB, it kept failing even if we increased the limits of nginx/ingress accordingly. axum has a default limit of 2MB payloads.
Increase the body limit of `/collect-receipts` to 3MB to match the limit we use in `/partial-voucher`
> fix: increase the body limit of /collect-receipts route

- Cargo.lock
- graph-gateway/Cargo.toml
- fix: await API keys before starting servers (87a4f21)
> release 20.0.2

- Cargo.lock
- gateway-framework/Cargo.toml
- gateway-framework/src/scalar/receipts.rs
The latest version of the TAP core crate (version 1.0.0) has been released, and this pull request updates the dependency to use this newest version.
> [!NOTE]
> This is a dependency for the alloy-rs crates upgrade to the latest version.
> chore(deps): update rust crate tap_core to 1.0.0

- Cargo.lock
- gateway-framework/Cargo.toml
The https://github.com/semiotic-ai/timeline-aggregation-protocol/pull/224 PR got merged. This PR pins the `tap_core` crate to this revision until a new release is available.
> chore(deps): pin rust crate tap_core to rev c179dfe

- Cargo.lock
- Cargo.toml
- graph-gateway/Cargo.toml
This is an intermediate upgrade (_pre-hyper v1_) of the `the graph` crates, so we have a step to revert if the upgrade does not go smoothly.
> chore(deps): update thegraph rust crates

- Cargo.lock
- Cargo.toml
- gateway-common/Cargo.toml
- gateway-framework/Cargo.toml
- graph-gateway/Cargo.toml
- graph-gateway/src/client_query.rs
- graph-gateway/src/client_query/legacy_auth_adapter.rs
- graph-gateway/src/client_query/query_selector.rs
- graph-gateway/src/client_query/rate_limiter.rs
- graph-gateway/src/client_query/require_auth.rs
- graph-gateway/src/main.rs
Upgrade all the hyper-related crates to the v1 era. This includes the following crates: `http`, `headers`, `hyper`, `tower-http`, `axum` and `axum-extra`, `reqwest`, and all the crates that have a transitive dependency on the hyper crate.
This PR resolves #541
> chore(deps): update hyper-related rust crates to v1

- Cargo.lock
- Cargo.toml
- gateway-framework/Cargo.toml
- gateway-framework/src/network/discovery.rs
- gateway-framework/src/network/indexing_performance.rs
- gateway-framework/src/network/mod.rs
- graph-gateway/Cargo.toml
- graph-gateway/src/client_query.rs
- graph-gateway/src/client_query/context.rs
- graph-gateway/src/indexers/indexing.rs
- graph-gateway/src/lib.rs
- graph-gateway/src/main.rs
This moves the indexing performance logic and `Status` struct into the `gateway_framework::network` module. That's it.
The PR is based on #673. I'll rebase it once that one has been merged.
> refactor: move more into the framework's network module

- Cargo.lock
- Cargo.toml
- gateway-framework/Cargo.toml
- gateway-framework/src/auth/context.rs
- gateway-framework/src/auth/methods/api_keys.rs
- gateway-framework/src/auth/methods/common.rs
- gateway-framework/src/auth/methods/mod.rs
- gateway-framework/src/auth/methods/subscriptions.rs
- gateway-framework/src/auth/mod.rs
- gateway-framework/src/http/middleware/mod.rs
- gateway-framework/src/http/middleware/rate_limiter.rs
- gateway-framework/src/http/middleware/require_auth.rs
- gateway-framework/src/http/mod.rs
- gateway-framework/src/lib.rs
- gateway-framework/src/reporting/kafka.rs
- gateway-framework/src/reporting/logging.rs
- gateway-framework/src/reporting/mod.rs
- graph-gateway/Cargo.toml
- graph-gateway/src/client_query.rs
- graph-gateway/src/config.rs
- graph-gateway/src/main.rs
- graph-gateway/src/subgraph_studio.rs
One step closer with the refactorings. This moves the `client_query/auth` module from the gateway into the framework. Along with this, the rate limiter and require auth middleware are also moved.
Small changes to API keys: the `APIKey` and `QueryStatus` types are moved into the framework, while the `AuthToken::StudioApiKey` enum variant is renamed to `AuthToken::ApiKey`. I think we can be opinionated here and establish the two forms of auth and this API key format as standard for other studios.
Based on #679, will need rebasing after that one is merged.
> refactor: move auth module and some middleware into the framework

- README.md
- docs/contributing.md
Add `contributing.md` to the project documentation. 
At this moment, this file only includes the instructions for managing the encrypted environment file.
> chore(docs): add contributing docs on how manage the project encrypted environment

- Cargo.lock
- Cargo.toml
- graph-gateway/Cargo.toml
- feat: use manifest from network subgraph (#647)
- feat: add API key support for `MONTHLY_CAP_REACHED` (#698)
- update candidate selection (3741528)
> release 20.1.0

- graph-gateway/src/indexers.rs
- graph-gateway/src/indexers/urls.rs
This PR introduces utility functions in the `indexers` client module to generate different indexer endpoints from a base URL (e.g., obtained from the graph network subgraph).
> feat(graph-gateway): add indexers url builder functions

- gateway-framework/src/auth/context.rs
- graph-gateway/src/main.rs
This PR is a minor refactoring (read, gardening 🪴) that moves all the initialization logic of the `AuthContext` (a.k.a. auth service) inside a function in the `main.rs` file.
~The PR also introduces the following minor reliability/robustness change:~
~- [x] Concurrently wait for the studio API keys and subscriptions to be fetched with a timeout of the 90s. If the credentials fetch fails or takes more than the timeout, the gateway will panic, indicating the failure cause.~
> refactor(graph-gateway): encapsulate the auth service initialization

- .github/workflows/ci.yml
The same way we did in the `edgeandnode/toolshed` repository's PR: https://github.com/edgeandnode/toolshed/pull/132
> Instead of adding every integration test environment variable to the GitHub actions secrets, this PR adds a _SOPS + Age_ encrypted environment file. This reduces the number of environment variables to add to the GHA secrets to 1: `IT_TESTS_AGE_KEY`.
> 
> As the file is encrypted with different Age recipients (read "public keys"), one can add a new environment variable using the `sops` command line and still be able to decrypt it locally and in the CI without the need for the GitHub repository admin rights. For now, the file is encrypted with the following recipients:
> 
> - GHA CI Age key: `age1r9h4sl458nt7f2j44tehw44xujg6rkp8w6vz7yp28aplf0aruq9qkvnapd`
> - LNSD …
> chore(graph-gateway): enable secrets dependent integration tests in the CI

- Cargo.lock
- Cargo.toml
- graph-gateway/Cargo.toml
- graph-gateway/src/client_query.rs
- update indexer-selection
- lower floor on `success_rate` score (https://github.com/edgeandnode/candidate-selection/commit/982afe85043085f056a0a01f05491b517a9ebc75)
- simplify combined non-perf scores (https://github.com/edgeandnode/candidate-selection/commit/7d29bbace1a9c17452c64ccecc5c9f0be8de0601)
- limit single indexer success rate (https://github.com/edgeandnode/candidate-selection/commit/931319456aff79ba9cdefd490367d243169a23ee)
- update graph-core
- fail fast when subgraph reorg is detected (https://github.com/edgeandnode/toolshed/pull/172)
- fix: include indexer status in candidate block range (#717)
> release 20.1.1

- gateway-framework/src/network/exchange_rate.rs
- graph-gateway/src/client_query.rs
- graph-gateway/src/client_query/context.rs
- graph-gateway/src/main.rs
This is the first step in my intentions to move away from eventuals. Based on how we use them, they provide little value while making it difficult to observe using standard tokio runtime tools.
> refactor(exchange_rate): replace eventual with watch

- .github/workflows/ci.yml
Fix the following warning:
```
Warning: Unexpected input(s) 'profile', 'override', valid inputs are ['toolchain', 'targets', 'target', 'components']
```
> chore(ci): fix rust-toolchain action warnings

- Cargo.lock
- gateway-framework/src/subscriptions/subgraph.rs
- graph-gateway/Cargo.toml
- graph-gateway/src/config.rs
- graph-gateway/src/main.rs
- fix(receipts): reduce legacy receipt overhead (#732)
- fix: reduce some unnecessary scheduler pressure (#727, #728, #729, #730, #733)
- update indexer-selection (#723)
- use u16 for ms latency (https://github.com/edgeandnode/candidate-selection/commit/8b18b43b3a8c3cbf3cfeb5d935b1e898d9caf773)
- rework perf decay (https://github.com/edgeandnode/candidate-selection/commit/f4f41e9c1d5a7f55f653a68fe24cb874df6c0748)
- increase decay rate (https://github.com/edgeandnode/candidate-selection/commit/fa044123c57d0b8c3f0da3e1ba087de5de2f7bdc)
- add slow decay frame (https://github.com/edgeandnode/candidate-selection/commit/303ea8806c58e501026c8db6fea9863517efe803)
- use 99th percentile in slow frame (https://github.com/edgeandnode/candidate-selection/commit/396c112b8b36bb863f7a3fbdaeabb26762da3375) …
> release 20.1.2

- graph-gateway/src/client_query.rs
- graph-gateway/src/lib.rs
- graph-gateway/src/sql_constraints.rs
As work takes place to [add support for SQL queries](https://github.com/graphprotocol/graph-node/pull/5382) the Gateway should invalidate such queries in the meantime.
The Gateway should reject queries containing SQL fields.
We want to reuse this code in the `sql-gateway`. Therefore we use the `SqlFieldBehavior` enum to inject the desired behavior.
---
Signed-off-by: Joseph Livesey <joseph@semiotic.ai>
> feat: add support for gateway to reject sql queries

- graph-gateway/src/config.rs
- graph-gateway/src/lib.rs
- graph-gateway/src/main.rs
As the `graph_gateway::config` is specific to the `graph-gateway` app, bind the config module to the `main.rs` file and decouple it from the `graph_gateway` library code.
> chore(graph-gateway): bind config to the gateway binary main

- Cargo.lock
- Cargo.toml
- graph-gateway/Cargo.toml
- graph-gateway/src/block_constraints.rs
- graph-gateway/src/client_query.rs
- graph-gateway/src/sql_constraints.rs
This changes the Agora context to only rely on a `&str` into the client request document to avoid unnecessary `String` allocations, and removes the need to copy the context for every indexer selected. Most of the changes are dedicated to indexer request rewrites, to avoid the need for `Context<_, String>`, while relying on `graphql_parser` to serialize everything below the top-level selection set fields.
> fix: inefficiencies in processing Agora contexts

- graph-gateway/src/network.rs
- graph-gateway/src/network/indexers_version_resolver.rs
Add a new resolver to the network module that encapsulates the indexer version's resolution with a configurable timeout.
> feat(graph-gateway): add indexer version resolver to network module

- graph-gateway/src/indexers/public_poi.rs
This checks off a `TODO` comment in `graph-gateway/src/indexers/public_poi.rs`, logging query response errors at trace level when merging.
Signed-off-by: Joseph Livesey [joseph@semiotic.ai](mailto:joseph@semiotic.ai)
> chore(graph-gateway): handle query response errors

- graph-gateway/src/main.rs
The pretty formatting of the config string makes the logs hard to read. Here's a snippet of the JSON:
```json
{"config":"Config {\n    api_keys: Some(\n        Endpoint {\n            url: Url {\n                scheme: \"https\",\n                cannot_be_a_base: false,\n                username: \"\",\n                password: None,\n                host: Some(\n                    Domain(\n                        
```
Signed-off-by: Joseph Livesey [joseph@semiotic.ai](mailto:joseph@semiotic.ai)
> chore(graph-gateway): do not pretty print config to logs

- Cargo.lock
- gateway-common/Cargo.toml
- gateway-common/src/lib.rs
- gateway-common/src/ptr.rs
- graph-gateway/src/network/indexer_indexing_cost_model_compiler.rs
- graph-gateway/src/network/internal/indexer_processing.rs
- graph-gateway/src/network/internal/snapshot.rs
As the `eventuals` crate is not maintained and the `Ptr` type provides a valuable optimization, I have added the `Ptr` type to the `gateway-common` crate.
This is an initial step to remove the dependency on the `eventuals` crate. Note that not all the `Ptr` usages can be replaced yet as some of them are tied to an associated _eventual_ type.
> feat(gateway-common): add cheap clone and compare ptr type

- gateway-common/src/caching.rs
- gateway-common/src/lib.rs
- graph-gateway/src/network.rs
- graph-gateway/src/network/indexer_indexing_cost_model_compiler.rs
- graph-gateway/src/network/indexer_indexing_cost_model_resolver.rs
- graph-gateway/src/network/indexer_indexing_progress_resolver.rs
- graph-gateway/src/network/indexer_version_resolver.rs
- graph-gateway/src/network/internal.rs
- graph-gateway/src/network/internal/indexer_processing.rs
- graph-gateway/src/network/internal/snapshot.rs
- graph-gateway/src/network/internal/tests/indexer_processing.rs
- graph-gateway/src/network/service.rs
- graph-gateway/tests/it_network_internal_fetch_update.rs
The indexer's information resolution process is susceptible to errors. For instance, an indexer can be overloaded and fail to respond at a specific moment, marking it as unavailable.
To prevent these information resolution errors from affecting the gateway's normal performance. To mitigate this issue, a TTL-limited caching mechanism has been implemented for different indexer information resolvers.
- The cache info is updated/refreshed if the info fetch is successful.
- If the info fetch fails, the data is fetched from the cache; if it is unavailable (or has expired), the fetch error is returned.
This PR is one of the remaining pieces of work before integrating the `network` service into the gateway.
> feat(graph-gateway): debounce network indexer info resolution errors

- gateway-framework/src/scalar/receipts.rs
- graph-gateway/src/indexer_client.rs
Tap Receipts now have their own header instead of sharing the header name with Scalar. This is due to a decision that TAP is a ground-up protocol instead of a continuation of Scalar.
> refactor: update header name for tap receipts

- graph-gateway/src/indexers/public_poi.rs
- graph-gateway/src/network/indexer_indexing_poi_resolver.rs
- graph-gateway/tests/it_indexers_status_public_pois.rs
Move the `merge_queries` function within the module where it is used. This makes the `indexers::public_pois` module a simple _pulic POIs_ client.
> refactor(graph-gateway): relocate indexers pois merge_queries logic

- graph-gateway/src/network/indexer_host_resolver.rs
- graph-gateway/src/network/internal/indexer_processing.rs
- graph-gateway/src/network/internal/state.rs
- graph-gateway/src/network/internal/tests/indexer_processing.rs
- graph-gateway/src/network/service.rs
- graph-gateway/tests/it_network_internal_fetch_update.rs
I am "sharding" the locks of the different indexer information resolvers' caches, one at a time. This way, we can use `parking_lot`'s `RwLock` instead of the `Tokyo`'s `RwLock.
> refactor(graph-gateway): shard network indexer host resolver cache lock

- graph-gateway/src/network/indexer_indexing_poi_blocklist.rs
- graph-gateway/src/network/indexer_indexing_poi_resolver.rs
- graph-gateway/src/network/internal/indexer_processing.rs
- graph-gateway/src/network/internal/state.rs
- graph-gateway/src/network/internal/tests/indexer_processing.rs
- graph-gateway/src/network/service.rs
This fixes a regression in which the public POI resolver sent requests to the indexer's base URL instead of the `/status` endpoint.
> fix(graph-gateway): use status endpoint for public pois resolution

- graph-gateway/src/network/indexer_indexing_cost_model_compiler.rs
- graph-gateway/src/network/indexer_indexing_cost_model_resolver.rs
- graph-gateway/src/network/indexer_indexing_progress_resolver.rs
- graph-gateway/src/network/indexer_version_resolver.rs
- graph-gateway/src/network/internal/indexer_processing.rs
- graph-gateway/src/network/internal/state.rs
- graph-gateway/src/network/internal/tests/indexer_processing.rs
- graph-gateway/src/network/service.rs
- graph-gateway/tests/it_network_internal_fetch_update.rs
> refactor(graph-gateway): shard remaining network indexer resolves cache locks

- graph-gateway/src/indexers/cost_models.rs
- graph-gateway/src/indexers/indexing_progress.rs
- graph-gateway/src/indexers/public_poi.rs
- graph-gateway/src/indexers/urls.rs
- graph-gateway/src/indexers/version.rs
- graph-gateway/src/network/indexer_indexing_poi_resolver.rs
- graph-gateway/src/network/indexer_indexing_progress_resolver.rs
- graph-gateway/src/network/indexer_version_resolver.rs
- graph-gateway/tests/it_indexers_status_version.rs
Recently, we had some bugs because we were querying the wrong endpoint. I added some `Url` new types to prevent this kind of bug.
> refactor(graph-gateway): differentiate indexer urls

- .github/workflows/ci.yml
- Cargo.lock
- gateway-framework/src/errors.rs
- graph-gateway/Cargo.toml
- graph-gateway/src/client_query.rs
- graph-gateway/src/indexer_client.rs
- graph-gateway/src/network.rs
- graph-gateway/src/network/config.rs
- graph-gateway/src/network/errors.rs
- graph-gateway/src/network/internal.rs
- graph-gateway/src/network/internal/indexer_processing.rs
- graph-gateway/src/network/internal/pre_processing.rs
- graph-gateway/src/network/internal/snapshot.rs
- graph-gateway/src/network/internal/state.rs
- graph-gateway/src/network/internal/subgraph_processing.rs
- graph-gateway/src/network/internal/tests/it_fetch_update.rs
- graph-gateway/src/network/internal/tests/it_indexer_processing.rs
- graph-gateway/src/network/internal/tests/tests_pre_processing.rs
- graph-gateway/src/network/internal/tests/tests_subgraph_processing.rs
- graph-gateway/src/network/service.rs
This is a major code iteration with the main goal of disambiguating the error messages returned by the gateway.
> feat(graph-gateway): rework network resolution error reporting

- Cargo.lock
- Cargo.toml
- gateway-framework/src/chain.rs
- graph-gateway/Cargo.toml
- graph-gateway/src/reports.rs
- fix(chain): improve block rate calculation for arbitrum-one
- update indexer-selection (increase `seconds_behind` sensitivity)
- fix(resports): avoid panic on shutdown
- feat(graph-gateway): rework network resolution error reporting (#839, #841)
> release 21.2.4

- gateway-framework/src/logging.rs
- graph-gateway/src/config.rs
- graph-gateway/src/indexers/public_poi.rs
- graph-gateway/src/main.rs
- graph-gateway/src/network/indexer_host_blocklist.rs
- graph-gateway/src/network/indexer_indexing_poi_blocklist.rs
- graph-gateway/src/network/internal/tests/it_indexer_processing.rs
- graph-gateway/src/network/service.rs
- graph-gateway/src/reports.rs
This is a ~small~ gardening 🪴 PR aiming to move some configuration runtime checks to the configuration parsing stage, and some other minor code refactorings:
> refactor(graph-gateway): simplify gateway configuration

- Cargo.lock
- graph-gateway/Cargo.toml
- fix: extra penalty for indexers over 30 minutes behind chain head (#846)
- fix: update indexer statuses when subgraph updates fail (#848)
- fix: indexing progress caching (#849)
> release 21.2.5

- gateway-framework/src/errors.rs
This makes sure we log all error responses back to the client, even if it doesn't fall into the main client query handler. Not sure if there's a cleaner way to do this.
> feat: log all response error messages

- graph-gateway/src/client_query.rs
The original intention of this was to apply this penalty when an indexer is more than 30 minutes behind chain head.
> fix: success rate cutoff at fixed time behind chain head

- gateway-framework/src/errors.rs
- graph-gateway/src/client_query.rs
User expectation is that, by default, indexers far behind chain head should not be responding. Especially when other indexers experience intermittent failures or timeouts.
> feat: add TooFarBehind error

- Cargo.lock
- Cargo.toml
- graph-gateway/src/client_query.rs
- graph-gateway/src/network/internal/snapshot.rs
- graph-gateway/src/network/service.rs
This should improve user experience by selecting the subgraph version outside of indexer-selection. Using indexer-selection hasn't been a perfect fit because it considers factors, such as expected latency, that do not line up with expectations for version selection. The downside of this change is that it opens up an abuse vector for indexers that claim a false indexing status. But we have decided it is reasonable to block such indexers.
> fix: select deployment outside of indexer-selection

- Cargo.lock
- graph-gateway/Cargo.toml
- fix: indexing progress cache, isolate by URL
- fix: remove excess timeout (#851)
- feat: log all response error messages (#852)
- fix: success rate cutoff at fixed time behind chain head (#853, #854)
- fix: select deployment outside of indexer-selection (#857)
> release 21.3.0

- graph-gateway/src/config.rs
- graph-gateway/src/main.rs
- graph-gateway/src/network/internal.rs
- graph-gateway/src/network/internal/tests/it_fetch_update.rs
- graph-gateway/src/network/service.rs
- graph-gateway/src/network/subgraph_client.rs
- graph-gateway/src/network/subgraph_client/core_paginated_client.rs
- graph-gateway/src/network/subgraph_client/indexers_list_paginated_client.rs
- graph-gateway/src/network/subgraph_client/indexers_list_paginated_client/inner_client.rs
- graph-gateway/src/network/subgraph_client/indexers_list_paginated_client/queries.rs
- graph-gateway/src/network/subgraph_client/paginated_client.rs
- graph-gateway/src/network/subgraph_client/tests/it_fetch_and_deserialize.rs
This PR removes the Gateway's dependency on the hosted service by adding a graph network subgraph client capable of directly querying an indexer from a configurable list of trusted indexer candidates.
This PR resolves #685
> feat(graph-gateway): add internal query client to network subgraph service

- graph-gateway/src/config.rs
- graph-gateway/src/lib.rs
- graph-gateway/src/main.rs
- graph-gateway/src/network/subgraph_client/indexers_list_paginated_client.rs
This removes the overhead of configuring fields that are functionally unused (indexer address), and avoids situations where we may want to query trusted indexers at different deployments.
> fix: remove extra configuration from network subgraph

- Cargo.lock
- gateway-framework/Cargo.toml
- graph-gateway/Cargo.toml
- fix: skip POI fetch until cache TTL expires (#860)
- feat: set gateway ID to signer address (#868)
- feat: add internal query client to network subgraph service (#856, #880)
- feat: direct indexer query API (#867)
- fix: remove deprecated data science logs (#882)
- `gateway_id` removed
- `network_subgraph` replaced by `trusted_indexers`
> release 22.0.0

- Cargo.lock
- Cargo.toml
- graph-gateway/src/indexer_client.rs
A change in the `DeploymentId` `std::fmt::Debug` trait has uncovered a bug in the graph gateway: We are constructing the indexer client's URL using the `std::fmt::Debug` trait (`"{:?}"`) instead of the `std::fmt::Display` trait (`"{}"`).
> fix(graph-gateway): use format display to construct the indexer url

- gateway-framework/src/auth.rs
- gateway-framework/src/http/middleware/require_auth.rs
- graph-gateway/src/client_query.rs
- graph-gateway/src/config.rs
- graph-gateway/src/main.rs
This adds a per API key rate limiter for the L1 deprecation strategy. Note that this will only be configured on the L1 gateway which only gets 5-15 queries per second total at the time of writing.
> feat: add rate limiter for L1 deprecation

- graph-gateway/src/indexer_client.rs
The gateway has been failing to provide indexer errors to consumers (just saying `no attestation`) in some cases because indexer-service is deviating from the expectations of [GraphQL over HTTP](https://graphql.org/learn/serving-over-http/#response). Instead of putting errors in the `errors`, it's using an `error` field. For example: `{"error": "GraphQL server error (client error): Invalid query variables provided"}`
> fix: handle indexer-service error format

- graph-gateway/src/client_query.rs
- graph-gateway/src/reports.rs
This adds the following fields to the client query kafka message:
- `request_bytes`: length of client query document in bytes
- `response_bytes` length of client query response (JSON serialized) in bytes
> feat(reports): add request & response bytes

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- fix: improve error message in network subgraph request (0973d28)
- feat: block indexers with deployment sets (#937)
- feat: add topic for TAP indexer fees (#938)
- fix: rename receipts config
- replace `bad_indexers` with `blocked_indexers`, which now supports additional features like blocking on a set of deployments
- rename `scalar` to `receipts`
> release 23.0.0

- Cargo.lock
- Cargo.toml
- fix: improve error message when trusted indexer fails to give timestamp (a3e259c)
> release 23.0.1

- README.md
- src/main.rs
- src/reports.rs
This replaces the `gateway_client_query_results`, `gateway_indexer_attempts`, and `gateway_indexer_fees` topics with a new `gateway_queries` topic.
part of #966
> kafka topic migration

- Cargo.lock
- Cargo.toml
- fix: remove ethers deps (2f64c18)
- fix: update exchange rate price feed (7ddfa9f)
- The GRT/USD exchange rate source watches contracts on Arbitrum One, rather than Ethereum mainnet. So the `exchange_rate_provider` should be set to an Arbitrum One RPC URL.
> release 24.3.0

- Cargo.lock
- Cargo.toml
- feat: add /blocklist route (#991)
- `poi_blocklist` entries have the following changes:
- rename `proof_of_indexing` -> `public_poi`
- rename `deployment_id` -> `deployment`
- add `query` (optional)
- add `bad_query_response` (optional)
> release 25.0.0

- Cargo.lock
- Cargo.toml
- src/auth.rs
- src/block_constraints.rs
- src/blocks.rs
- src/chain.rs
- src/client_query.rs
- src/client_query/attestation_header.rs
- src/client_query/context.rs
- src/config.rs
- src/errors.rs
- src/exchange_rate.rs
- src/indexer_client.rs
- src/indexers/indexing_progress.rs
- src/indexers/public_poi.rs
- src/indexing_performance.rs
- src/main.rs
- src/network/indexer_indexing_poi_blocklist.rs
- src/network/indexer_indexing_poi_resolver.rs
- src/network/indexer_indexing_progress_resolver.rs
- src/network/internal/indexer_processing.rs
- src/network/internal/snapshot.rs
- src/network/internal/state.rs
- src/network/internal/subgraph_processing.rs
- src/network/service.rs
- src/network/subgraph_client.rs
- src/receipts.rs
- src/reports.rs
- src/vouchers.rs
This pull request includes several changes to the `Cargo.toml` file and multiple Rust source files to update dependencies and refactor import paths. The main changes involve updating versions of dependencies and modifying import paths to use the re-exported `thegraph_core::alloy::primitives` module.
Dependency updates:
* Updated `alloy` dependency to remove specific features and added new features to `thegraph-core` dependency in `Cargo.toml`.
Refactor import paths:
* Changed import paths from `alloy` to `thegraph_core::alloy::primitives` in various source files, including `src/auth.rs`, `src/block_constraints.rs`, `src/blocks.rs`, `src/chain.rs`, `src/client_query.rs`, and more.
These changes ensure the codebase uses the updated dependency versions, _v0.8.5_, and the correct import paths …
> chore(deps): update rust crate thegraph-core to v0.8.5

- Cargo.lock
- Cargo.toml
This pull request includes updates to dependencies and features in the `Cargo.toml` file. The most important changes are updating the `tap_core` and `thegraph-core` dependencies.
* Updated `tap_core` to a new revision `1c6e29f` from the previous revision `f680f4c`.
* Updated `thegraph-core` version to `0.9.0` from `0.8.5` and included additional features.
> chore(deps): update rust crate thegraph-core to v0.9.0

- Cargo.lock
- Cargo.toml
- fix: remove Scalar support (#998)
- feat: remove support for API key max_budget (#983)
- remove `receipts.legacy_signer`
- `min_indexer_version` should be set to a value of at least `1.0.0-alpha`
> release 26.0.0

- src/config.rs
- src/main.rs
- src/network.rs
- src/network/indexer_blocklist.rs
- src/network/indexer_processing.rs
- src/network/poi_filter.rs
- src/network/service.rs
This merges the PoI and indexer blocklists, such that the new blocklist is served via `/blocklist`. Also, a kafka consumer is added to update blocklist entries from the `gateway_blocklist` topic.
> feat: dynamic blocklist

- src/main.rs
This sets the content-type for metrics to `text/plain` instead of `application/octet-stream`.
fixes #1029
> fix: metrics content-type

- Cargo.lock
- Cargo.toml
- src/exchange_rate.rs
- src/receipts.rs
This pull request includes several changes to update dependencies, refactor code, and simplify type usage. The relevant changes are listed below.
* Replace the `tap_core` dependency to `tap_graph` with a new revision in `Cargo.toml`.
* Refactored imports in `src/exchange_rate.rs` to use the `Provider` trait and updated the `fetch_price` function to accept an `impl Provider`. [[1]](diffhunk://#diff-c59fb55633d927233636c150a8177ecd5ff4bc2fd0d4f41b09084c7165b4a4b5L7-R9) [[2]](diffhunk://#diff-c59fb55633d927233636c150a8177ecd5ff4bc2fd0d4f41b09084c7165b4a4b5L21-L23) [[3]](diffhunk://#diff-c59fb55633d927233636c150a8177ecd5ff4bc2fd0d4f41b09084c7165b4a4b5L61-R60)
* Replaced `EIP712SignedMessage` with `SignedReceipt` in `src/receipts.rs` and updated related code to use the new type. …
> chore(deps): upgrade to latest thegraph-core version
